title:              Slave to the Boat
email:              jaredjensen71@gmail.com
description:        Follow along as we fix the boat and occasionally even go cruising
author:             Jared Jensen
baseurl:            "/"
url:                "https://slavetotheboat.com"

# Social Profiles
twitter_username:   
github_username:    jaredjensen
facebook_username:  snarkcon5
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   # UA-XXXXXXXXX-X # out your google-analytics code

formspree:
  path: f/mgeddrzv

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

kramdown:  
  parse_block_html: true
